### PR TITLE
Mher 66

### PR DESCRIPTION
**Pull request by hnnesv**
MHER-66

@rcrichton if you could please test / review?

screen shot 2016-06-13 at 14 36 52
screen shot 2016-06-13 at 14 37 32
screen shot 2016-06-13 at 14 38 31
screen shot 2016-06-13 at 14 39 00

### CODE REVIEW

**Comment by rcrichton** [comment]
@hnnesv commenting just on the functionality for now, this is looking great! There are just two thing that I think will make this a simpler experience:
1. The user should be able choose the initial role for each document rather than it defaulting to the document name.
2. When setting roles for individual storied queries it would be great to be able to provide a range of queries to set to the same role, I think this will be a common use case. Perhaps this could be done by having an option in the 'Edit <document>' menu which reads 'Set role for individual stored queries', then when selected the user gets a list of stored queries and is asked to enter a range to set to the same role. There are packages similar to this to handle ranges - https://www.npmjs.com/package/parse-numeric-range. (It may also be nice to bundle multiple stored queries up into a single channel if they have the same role, but that may lead to a crazy long url pattern...)

What do you think?

**Comment by rcrichton** [comment]
Also, after we submit to the OpenHIM I think the commands need to be shown again.

**Comment by hnnesv** [comment]
@rcrichton sounds good - let me see what I can do.

**Comment by hnnesv** [comment]
@rcrichton I've incorporated your feedback if you could please review? thanks

**Comment by rcrichton** [comment]
LGTM :+1:

**Pull request merged**
