### PR TITLE
MHER-56: Remove fake function call

### PR DESCRIPTION
**Pull request by napiergit**
Hi @rcrichton, can you please review and/or advise if I am on the right track.

### CODE REVIEW

**Comment by napiergit** [comment]
This pull request looks funny because I pushed my initial commit to master.

**Comment by rcrichton** [comment]
Cool looks good. I just don't see how the `options` are set for the `http.get`. Also, we may not want to pass in all the options, maybe those should be read from a config file rather? (well all except the url which can be static).

Perhaps try reset master back to no commits so it's easierr to review. Maybe something like this would work - http://stackoverflow.com/a/15454834/588776. Don't worry about it if it turns out to be hard.

**Comment by napiergit** [comment]
@rcrichton, ready for second round review.

**Comment by rcrichton** [comment]
Cool, looks good to me. :+1:

**Pull request merged**
